### PR TITLE
BUG: Improving the allignment of Login page

### LINKED ISSUE #1: BUG: Form Allignment is bad
Login form is not align properly.

form

Please assign to me this issue under gssoc-ext and hacktoberfest-accepted with level-2:)

### PR DESCRIPTION
**Pull request by harshbhar0629**
Improving the allignment of login page and now it looks good!
Fixes #1 

loginPage

### CODE REVIEW

**Comment by vaibhavyadav-dev** [comment]
@harshbhar0629 can you pull the latest commits and again make PR to pass all the checks.

**Comment by harshbhar0629** [comment]
Current login page:)

login1

**Comment by vaibhavyadav-dev** [comment]
@harshbhar0629 provide full screenshot of working webpage you've changed!

**Comment by harshbhar0629** [comment]
Full Image

fullImgLogin

**Comment by harshbhar0629** [comment]
Please merge my PR with labels:)

**Pull request merged**
