### PR TITLE
Bug/register page allignment

### LINKED ISSUE #2: BUG: Register form allignment
Register form allignment:

registerForm

Please assign to me under gssoc-ext and hacktoberfest-accepted with the level-2.

### PR DESCRIPTION
**Pull request by harshbhar0629**
Fixes #2 Improving the allignment of Register page.

register1

register2

### CODE REVIEW

**Comment by vaibhavyadav-dev** [comment]
@harshbhar0629 fix this text it is misaligned and share your full screenshot I want to know where you've placed the side text


image

Rest looks good 💯

**Comment by harshbhar0629** [comment]
Ok

**Comment by harshbhar0629** [comment]
@vaibhavyadav-dev Please review it again:)
Current UI:

RegisterForm

**Comment by harshbhar0629** [comment]
Is this repo paticipate in gssoc??

**Pull request merged**
